resume_dataset_path: "data/resume/selected_cats_resumes.csv"

inference_mode: gpu_forward_pass     # REQUIRED (e.g. gpu_forward_pass, gpu_inference, perform_ablations, …)

random_seed: 42

model_name: "mistralai/Ministral-8B-Instruct-2410"

anti_bias_statement_file: "anti_bias_statements.txt"
job_description_file: "job_description.txt"
system_prompt_filename: "yes_no.txt"
anti_bias_statement_folder: "generated_anti_bias_statements"
job_description_folder: "job_descriptions"

email_domain: "gmail"

industry: "INFORMATION-TECHNOLOGY"
mode: "full"
political_orientation: false
pregnancy: false
employment_gap: false
anthropic_dataset: false
downsample: null                 # integer or null
steering_intervention: false
ablation_intervention: false
intervention_strength: 0.0
intervened_features: []          # list of feature names
no_names: false

# Ablation-only parameters
scale: 0.0
bias_type: "N/A"