resume_dataset_path: "data/resume/selected_cats_resumes.csv"

# inference_mode: gpu_forward_pass     # REQUIRED (e.g. gpu_forward_pass, gpu_inference, perform_ablations, …)
# inference_mode: perform_ablations
inference_mode: open_router

random_seed: 42

model_name: ""

anti_bias_statement_file: ""
job_description_file: ""
system_prompt_filename: "yes_no.txt"
anti_bias_statement_folder: "anti_bias_statements"
job_description_folder: "job_descriptions"

email_domain: "gmail"

industry: "INFORMATION-TECHNOLOGY"
anthropic_dataset: false
downsample: 50
no_names: false
college_name_only: true

# Ablation-only parameters
scale: 1000.0
bias_type: "N/A"

model_names_to_iterate:
  # - "mistralai/Mistral-Small-24B-Instruct-2501"
  # - "google/gemma-2-27b-it"
  # - "openai/gpt-4o-2024-08-06"
  - "google/gemini-2.5-flash-preview-05-20"

anti_bias_statement_files_to_iterate:
  - "v2.txt"

job_description_files_to_iterate:
  - "meta_job_description.txt"

scales_to_iterate:
  - 1000.0

bias_types_to_iterate:
  - "N/A"


    # model_names = [
    #             "google/gemma-2-2b-it",
    #             # "google/gemma-2-27b-it",
    #             # "google/gemma-2-9b-it",
    #             # "mistralai/Ministral-8B-Instruct-2410",
    #             # "mistralai/Mistral-Small-24B-Instruct-2501",
    #             # "deepseek/deepseek-r1",
    #             # "openai/gpt-4o-2024-08-06",
    #             # "deepseek/deepseek-r1-distill-llama-70b"
    #             # "openai/o1-mini-2024-09-12",
    #             # "openai/o1-mini",
    #             # "openai/o1"
    #             # "x-ai/grok-3-mini-beta"
    #             # "qwen/qwq-32b",
    #             # "anthropic/claude-3.7-sonnet"
    #             # "anthropic/claude-3.7-sonnet:thinking",
    #             # "qwen/qwen2.5-32b-instruct",
    #             # "openai/gpt-4o-mini",
    #         ]